data(women)
height_factor <- factor(women$height)
print(height_factor)
print(levels(height_factor))
letter_sample <- sample(LETTERS, 5)
letter_factor <- factor(letter_sample)
print(letter_factor)
print(levels(letter_factor))
print(nlevels(letter_factor))