num <- c(10, 20, 30, 40, 50)
char <- c("Apple", "Banana", "Mango", "Orange")
logical <- c(TRUE, FALSE, TRUE, FALSE)
print(num)
print(typeof(num))
print(char)
print(typeof(char))
print(logical)
print(typeof(logical))